{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-websearch.fullname" . }}-secrets
  labels:
    {{- include "ai-websearch.labels" . | nindent 4 }}
type: Opaque
data:
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | b64enc | quote }}
  TAVILY_API_KEY: {{ .Values.secrets.tavilyApiKey | b64enc | quote }}
  WEBUI_SECRET_KEY: {{ .Values.secrets.webuiSecretKey | b64enc | quote }}
{{- end }}
