apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-websearch.fullname" . }}-secrets
  labels:
    {{- include "ai-websearch.labels" . | nindent 4 }}
type: Opaque
data:
  groq-api-key: {{ .Values.secrets.groqApiKey | b64enc | quote }}
  tavily-api-key: {{ .Values.secrets.tavilyApiKey | b64enc | quote }}
  webui-secret-key: {{ .Values.secrets.webuiSecretKey | b64enc | quote }}
